// This file was autogenerated by /Users/ito/projects/webos-goodies/blog/articles/building_ui_from_html_using_closure_library/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/app.js', ['app.App'], ['goog.dom', 'goog.ui.Toolbar', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarToggleButton']);
