(function(){var h=void 0,i=null,k,n=this;function aa(a){for(var a=a.split("."),b=n,c;c=a.shift();)if(b[c]!=i)b=b[c];else return i;return b}function p(){}
function ba(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ca(a){return ba(a)=="array"}function da(a){var b=ba(a);return b=="array"||b=="object"&&typeof a.length=="number"}function r(a){return typeof a=="string"}function ea(a){return ba(a)=="function"}function fa(a){a=ba(a);return a=="object"||a=="array"||a=="function"}function ga(a){return a[ha]||(a[ha]=++ia)}var ha="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ia=0;
function ja(a,b,c){return a.call.apply(a.bind,arguments)}function ka(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}function s(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ja:ka;return s.apply(i,arguments)}var la=Date.now||function(){return+new Date};
function t(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c};var ma=/^[a-zA-Z0-9\-_.!~*'()]*$/;function na(a){a=String(a);return!ma.test(a)?encodeURIComponent(a):a}function oa(a){if(!pa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(qa,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(ra,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(sa,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(ta,"&quot;"));return a}var qa=/&/g,ra=/</g,sa=/>/g,ta=/\"/g,pa=/[&<>\"]/;
function ua(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(d.length,f.length),g=0;c==0&&g<e;g++){var j=d[g]||"",l=f[g]||"",m=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var o=m.exec(j)||["","",""],v=q.exec(l)||["","",""];if(o[0].length==0&&v[0].length==0)break;c=va(o[1].length==0?0:parseInt(o[1],10),v[1].length==0?0:parseInt(v[1],10))||va(o[2].length==0,v[2].length==0)||va(o[2],v[2])}while(c==
0)}return c}function va(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};function wa(a,b){for(var c in a)b.call(h,a[c],c,a)}var xa="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function ya(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<xa.length;e++)c=xa[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function za(a){for(var b=[],c=0;c<a.length;c+=2){var d=a[c],f=a[c+1],e=b;if(ca(f))for(var g=0;g<f.length;g++)e.push("&",d),f[g]!==""&&e.push("=",na(f[g]));else f!=i&&(e.push("&",d),f!==""&&e.push("=",na(f)))}b[0]="";return b.join("")}function Aa(a,b,c,d){for(var f=c.length;(b=a.indexOf(c,b))>=0&&b<d;){var e=a.charCodeAt(b-1);if(e==38||e==63)if(e=a.charCodeAt(b+f),!e||e==61||e==38||e==35)return b;b+=f+1}return-1}var Ba=/#|$/,Ca=/[?&]($|#)/;
function Da(a,b){for(var c=a.search(Ba),d=0,f,e=[];(f=Aa(a,d,b,c))>=0;)e.push(a.substring(d,f)),d=Math.min(a.indexOf("&",f)+1||c,c);e.push(a.substr(d));return e.join("").replace(Ca,"$1")};var u,Ea,Fa,Ga,Ha;function Ia(){return n.navigator?n.navigator.userAgent:i}Ha=Ga=Fa=Ea=u=!1;var Ja;if(Ja=Ia()){var Ka=n.navigator;u=Ja.indexOf("Opera")==0;Ea=!u&&Ja.indexOf("MSIE")!=-1;Ga=(Fa=!u&&Ja.indexOf("WebKit")!=-1)&&Ja.indexOf("Mobile")!=-1;Ha=!u&&!Fa&&Ka.product=="Gecko"}var x=Ea,La=Ha,Ma=Fa,Na=Ga,Oa=n.navigator,Pa=(Oa&&Oa.platform||"").indexOf("Mac")!=-1,Qa;
a:{var Ra="",Sa;if(u&&n.opera)var Ta=n.opera.version,Ra=typeof Ta=="function"?Ta():Ta;else if(La?Sa=/rv\:([^\);]+)(\)|;)/:x?Sa=/MSIE\s+([^\);]+)(\)|;)/:Ma&&(Sa=/WebKit\/(\S+)/),Sa)var Ua=Sa.exec(Ia()),Ra=Ua?Ua[1]:"";if(x){var Va,Wa=n.document;Va=Wa?Wa.documentMode:h;if(Va>parseFloat(Ra)){Qa=String(Va);break a}}Qa=Ra}var Xa={};function Ya(a){return Xa[a]||(Xa[a]=ua(Qa,a)>=0)}var Za={};function $a(){return Za[9]||(Za[9]=x&&document.documentMode&&document.documentMode>=9)};var y=Array.prototype,z=y.indexOf?function(a,b,c){return y.indexOf.call(a,b,c)}:function(a,b,c){c=c==i?0:c<0?Math.max(0,a.length+c):c;if(r(a))return!r(b)||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ab=y.forEach?function(a,b,c){y.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=r(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function bb(a){return y.concat.apply(y,arguments)}
function cb(a){if(ca(a))return bb(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function db(a,b,c,d){y.splice.apply(a,eb(arguments,1))}function eb(a,b,c){return arguments.length<=2?y.slice.call(a,b):y.slice.call(a,b,c)}function A(a,b){return a>b?1:a<b?-1:0};function fb(a){return gb(a||arguments.callee.caller,[])}
function gb(a,b){var c=[];if(z(b,a)>=0)c.push("[...circular reference...]");else if(a&&b.length<50){c.push(hb(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){f>0&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=hb(e))?e:"[fn]";break;default:e=typeof e}e.length>40&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(gb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function hb(a){if(ib[a])return ib[a];a=String(a);if(!ib[a]){var b=/function ([^\(]+)/.exec(a);ib[a]=b?b[1]:"[Anonymous]"}return ib[a]}var ib={};function B(a,b,c,d,f){this.reset(a,b,c,d,f)}B.prototype.Oa=0;B.prototype.ia=i;B.prototype.ha=i;var jb=0;B.prototype.reset=function(a,b,c,d,f){this.Oa=typeof f=="number"?f:jb++;this.Va=d||la();this.u=a;this.Ga=b;this.Ua=c;delete this.ia;delete this.ha};B.prototype.wa=function(a){this.u=a};function C(a){this.Ha=a}C.prototype.I=i;C.prototype.u=i;C.prototype.M=i;C.prototype.ka=i;function kb(a,b){this.name=a;this.value=b}kb.prototype.toString=function(){return this.name};var lb=new kb("WARNING",900),mb=new kb("CONFIG",700);C.prototype.getParent=function(){return this.I};C.prototype.wa=function(a){this.u=a};function nb(a){return a.u?a.u:a.I?nb(a.I):i}
C.prototype.log=function(a,b,c){if(a.value>=nb(this).value){a=this.Da(a,b,c);b="log:"+a.Ga;n.console&&(n.console.timeStamp?n.console.timeStamp(b):n.console.markTimeline&&n.console.markTimeline(b));n.msWriteProfilerMark&&n.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.ka)for(var f=0,e=h;e=c.ka[f];f++)e(d);b=b.getParent()}}};
C.prototype.Da=function(a,b,c){var d=new B(a,String(b),this.Ha);if(c){d.ia=c;var f;var e=arguments.callee.caller;try{var g;var j=aa("window.location.href");if(r(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:j,stack:"Not available"};else{var l,m,q=!1;try{l=c.lineNumber||c.Ta||"Not available"}catch(o){l="Not available",q=!0}try{m=c.fileName||c.filename||c.sourceURL||j}catch(v){m="Not available",q=!0}g=q||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,
lineNumber:l,fileName:m,stack:c.stack||"Not available"}:c}f="Message: "+oa(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+oa(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+oa(fb(e)+"-> ")}catch(w){f="Exception trying to expose exception! You win, we lose. "+w}d.ha=f}return d};function ob(a,b){a.log(lb,b,h)}var pb={},qb=i;
function D(a){qb||(qb=new C(""),pb[""]=qb,qb.wa(mb));var b;if(!(b=pb[a])){b=new C(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=D(a.substr(0,c));if(!c.M)c.M={};c.M[d]=b;b.I=c;pb[a]=b}return b};function E(a,b){this.label=this.e=a;this.description=b;this.ca=[]}E.prototype.i=D("goog.tweak.BaseEntry");E.prototype.w=!0;function rb(a,b){a.ca.push(b)}E.prototype.ja=function(){for(var a=0,b;b=this.ca[a];++a)b(this)};function F(a,b){E.call(this,a,b);this.l=this.e.toLowerCase()}t(F,E);F.prototype.i=D("goog.tweak.BaseSetting");F.prototype.G=0;F.prototype.Z=function(a){this.l=a};function sb(a){if(a.G==0)a.G=1,a.F(a.V==h?i:a.V),a.G=2}function G(a,b,c){F.call(this,a,b);this.d=c}t(G,F);
G.prototype.i=D("goog.tweak.BasePrimitiveSetting");function H(a){sb(a);return a.X}function I(a,b){sb(a);var c=a.X!=b;a.X=b;if(a.G==1)a.Ra=b;else{if(!a.w)a.Ra=b;c&&a.ja()}}G.prototype.S=function(){sb(this);return this.X==this.d?i:this.P()};function J(a,b){G.call(this,a,b,"")}t(J,G);J.prototype.i=D("goog.tweak.StringSetting");J.prototype.P=function(){return H(this)};J.prototype.xa=function(a){if((this.p=a)&&!(z(a,this.d)>=0))this.d=a[0]};
J.prototype.F=function(a){if(a==i)I(this,this.d);else{var b=this.p;if(b){for(var a=a.toLowerCase(),c=0,d=b.length;c<d;++c)if(a==b[c].toLowerCase()){I(this,b[c]);return}ob(this.i,"Tweak "+this.e+" has value outside of expected range:"+a)}I(this,a)}};function K(a,b){G.call(this,a,b,0)}t(K,G);K.prototype.i=D("goog.tweak.NumericSetting");K.prototype.P=function(){return""+H(this)};K.prototype.xa=function(a){if((this.p=a)&&!(z(a,this.d)>=0))this.d=a[0]};
K.prototype.F=function(a){if(a==i)I(this,this.d);else{var b=+a;this.p&&!(z(this.p,b)>=0)&&ob(this.i,"Tweak "+this.e+" has value outside of expected range: "+a);isNaN(b)?(ob(this.i,"Tweak "+this.e+" has value of NaN, resetting to "+this.d),I(this,this.d)):I(this,b)}};function L(a,b){G.call(this,a,b,!1)}t(L,G);L.prototype.i=D("goog.tweak.BooleanSetting");L.prototype.P=function(){return H(this)?"1":"0"};L.prototype.F=function(a){a==i?I(this,this.d):(a=a.toLowerCase(),I(this,a=="true"||a=="1"))};
function M(a,b,c){L.call(this,a,b);this.$=this.e.toLowerCase();this.Ea=c;M.o.Z.call(this,i)}t(M,L);M.prototype.i=D("goog.tweak.BooleanInGroupSetting");M.prototype.Z=function(){};function N(a,b){F.call(this,a,b);this.A={};this.sa={}}t(N,F);N.prototype.i=D("goog.tweak.BooleanGroup");N.prototype.F=function(a){var b={};if(a)for(var a=a.split(/\s*,\s*/),c=0;c<a.length;++c){var d=a[c].toLowerCase(),f=d.charAt(0)=="-";f&&(d=d.substr(1));b[d]=!f}this.sa=b};
N.prototype.S=function(){sb(this);var a=[],b=this.A,c=[],d=0,f;for(f in b)c[d++]=f;c.sort();for(b=0;d=this.A[c[b]];++b)d.S()!=i&&a.push((H(d)?"":"-")+d.$);return a.length?a.join(","):i};function tb(a,b,c){E.call(this,a,b);rb(this,c);this.w=!1}t(tb,E);function ub(a,b){this.B={};for(var c=a.substr(1).split("&"),d={},f=0,e=c.length;f<e;++f){var g=c[f].split("=");g[0]&&(d[decodeURIComponent(g[0].replace(/\+/g," ")).toLowerCase()]=decodeURIComponent((g[1]||"").replace(/\+/g," ")))}this.La=d;this.pa=[];this.da=b;this.Aa={}}ub.prototype.Fa=D("goog.tweak.Registry");function vb(a,b){var c=[],d;for(d in a.B){var f=a.B[d];if(f instanceof F){if(!f.l)continue}else if(b)continue;c.push(f)}return c}
function wb(a){var b=window.location.search,a=vb(a,!0);a.sort(function(a,b){return A(a.l,b.l)});for(var c=[],d=0,f;f=a[d];++d){var e=f.S();e!=i&&c.push(f.l,e);b=Da(b,encodeURIComponent(f.l))}a=za(c);a=a.replace(/%2C/g,",").replace(/%20/g,"+");return!a?b:b?b+"&"+a:"?"+a};var xb=i,O=i;function yb(){xb||(xb=new ub(window.location.search,{}));return xb}
function P(a,b,c){if(c){if(c.label)a.label=c.label,delete c.label;c.K&&(a.xa(c.K),delete c.K);c.qa!==h&&(a.Z(c.qa),delete c.qa);if(c.ua!==h)a.w=c.ua,delete c.ua;c.ba&&(rb(a,c.ba),delete c.ba);if(c.ya)a.$=c.ya,delete c.ya;for(var d in c);}if(b!=h)a.d=b;if(O&&(b=O,sb(b),c=a.$.toLowerCase(),b.A[c]=a,b=b.sa[c],b!=h))a.V=b?"1":"0";b=yb();c=a.e;if((d=b.B[c])&&d==a)ob(b.Fa,"Tweak entry registered twice: "+c);else{d=c in b.da?b.da[c]:b.Aa[c];if(d!==h)a.d=d;if(a instanceof F&&a.l)a.V=b.La[a.l];b.B[c]=a;for(c=
0;d=b.pa[c];++c)d(a)}}function zb(a,b,c){a=O?new M(a,b,O):new L(a,b);P(a,c,h)};var Ab;function Bb(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function Cb(a,b){var c=Bb(a),d=eb(arguments,1),f;f=c;for(var e=0,g=0;g<d.length;g++)z(f,d[g])>=0||(f.push(d[g]),e++);f=e==d.length;a.className=c.join(" ");return f}function Db(a,b){for(var c=Bb(a),d=eb(arguments,1),f=c,e=0,g=0;g<f.length;g++)z(d,f[g])>=0&&(db(f,g--,1),e++);a.className=c.join(" ")};var Eb=!x||$a();!La&&!x||x&&$a()||La&&Ya("1.9.1");x&&Ya("9");function Fb(a){return a?new Q(a.nodeType==9?a:a.ownerDocument||a.document):Ab||(Ab=new Q)}
function Gb(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(!Ma||document.compatMode=="CSS1Compat"||Ya("528"))&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName)if(a=a.getElementsByClassName(c),b){for(var d={},f=0,e=0,g;g=a[e];e++)b==g.nodeName&&(d[f++]=g);d.length=f;return d}else return a;a=a.getElementsByTagName(b||"*");if(c){d={};for(e=f=0;g=a[e];e++)b=g.className,typeof b.split=="function"&&z(b.split(/\s+/),c)>=0&&(d[f++]=
g);d.length=f;return d}else return a}function Hb(a,b){wa(b,function(b,d){d=="style"?a.style.cssText=b:d=="class"?a.className=b:d=="for"?a.htmlFor=b:d in Ib?a.setAttribute(Ib[d],b):d.lastIndexOf("aria-",0)==0?a.setAttribute(d,b):a[d]=b})}var Ib={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function Jb(a,b,c){function d(c){c&&b.appendChild(r(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];if(da(e)&&!(fa(e)&&e.nodeType>0)){var g;a:{if(e&&typeof e.length=="number")if(fa(e)){g=typeof e.item=="function"||typeof e.item=="string";break a}else if(ea(e)){g=typeof e.item=="function";break a}g=!1}ab(g?cb(e):e,d)}else d(e)}}
function Kb(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild((a.nodeType==9?a:a.ownerDocument||a.document).createTextNode(b))}}function Q(a){this.a=a||n.document||document}
Q.prototype.b=function(a,b,c){var d=this.a,f=arguments,e=f[0],g=f[1];if(!Eb&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',oa(g.name),'"');if(g.type){e.push(' type="',oa(g.type),'"');var j={};ya(j,g);g=j;delete g.type}e.push(">");e=e.join("")}e=d.createElement(e);if(g)r(g)?e.className=g:ca(g)?Cb.apply(i,[e].concat(g)):Hb(e,g);f.length>2&&Jb(d,e,f);return e};Q.prototype.createElement=function(a){return this.a.createElement(a)};Q.prototype.createTextNode=function(a){return this.a.createTextNode(a)};
Q.prototype.appendChild=function(a,b){a.appendChild(b)};function Lb(a,b){a.style.display=b?"":"none"}function Mb(a){var b=Nb;x?a.cssText=b:a[Ma?"innerText":"innerHTML"]=b};var Ob;var Pb="click",Qb="keydown";!x||$a();var Rb=x&&!Ya("8");function R(){}R.prototype.ga=!1;R.prototype.q=function(){if(!this.ga)this.ga=!0,this.h()};R.prototype.h=function(){this.Ba&&Sb.apply(i,this.Ba)};function Sb(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];da(d)?Sb.apply(i,d):d&&typeof d.q=="function"&&d.q()}};function S(a,b){this.type=a;this.currentTarget=this.target=b}t(S,R);k=S.prototype;k.h=function(){delete this.type;delete this.target;delete this.currentTarget};k.n=!1;k.z=!0;k.stopPropagation=function(){this.n=!0};k.preventDefault=function(){this.z=!1};function Tb(a){Tb[" "](a);return a}Tb[" "]=p;function T(a,b){a&&this.D(a,b)}t(T,S);k=T.prototype;k.target=i;k.relatedTarget=i;k.offsetX=0;k.offsetY=0;k.clientX=0;k.clientY=0;k.screenX=0;k.screenY=0;k.button=0;k.keyCode=0;k.charCode=0;k.ctrlKey=!1;k.altKey=!1;k.shiftKey=!1;k.metaKey=!1;k.Ma=!1;k.r=i;
k.D=function(a,b){var c=this.type=a.type;S.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(La){var f;a:{try{Tb(d.nodeName);f=!0;break a}catch(e){}f=!1}f||(d=i)}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Ma=Pa?a.metaKey:a.ctrlKey;this.state=a.state;this.r=a;delete this.z;delete this.n};k.stopPropagation=function(){T.o.stopPropagation.call(this);this.r.stopPropagation?this.r.stopPropagation():this.r.cancelBubble=!0};
k.preventDefault=function(){T.o.preventDefault.call(this);var a=this.r;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Rb)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};k.h=function(){T.o.h.call(this);this.relatedTarget=this.currentTarget=this.target=this.r=i};function Ub(){}var Vb=0;k=Ub.prototype;k.key=0;k.s=!1;k.aa=!1;k.D=function(a,b,c,d,f,e){if(ea(a))this.la=!0;else if(a&&a.handleEvent&&ea(a.handleEvent))this.la=!1;else throw Error("Invalid listener argument");this.v=a;this.ra=b;this.src=c;this.type=d;this.capture=!!f;this.U=e;this.aa=!1;this.key=++Vb;this.s=!1};k.handleEvent=function(a){return this.la?this.v.call(this.U||this.src,a):this.v.handleEvent.call(this.v,a)};var Wb,Xb=(Wb="ScriptEngine"in n&&n.ScriptEngine()=="JScript")?n.ScriptEngineMajorVersion()+"."+n.ScriptEngineMinorVersion()+"."+n.ScriptEngineBuildVersion():"0";function U(a,b){this.na=b;this.m=[];if(a>this.na)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var c=0;c<a;c++)this.m.push(this.j?this.j():{})}t(U,R);U.prototype.j=i;U.prototype.fa=i;U.prototype.getObject=function(){return this.m.length?this.m.pop():this.j?this.j():{}};function Yb(a,b){a.m.length<a.na?a.m.push(b):Zb(a,b)}function Zb(a,b){if(a.fa)a.fa(b);else if(fa(b))if(ea(b.q))b.q();else for(var c in b)delete b[c]}
U.prototype.h=function(){U.o.h.call(this);for(var a=this.m;a.length;)Zb(this,a.pop());delete this.m};var $b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc;
(function(){function a(){return{g:0,f:0}}function b(){return[]}function c(){function a(b){b=g.call(a.src,a.key,b);if(!b)return b}return a}function d(){return new Ub}function f(){return new T}var e=Wb&&!(ua(Xb,"5.7")>=0),g;ec=function(a){g=a};if(e){$b=function(){return j.getObject()};ac=function(a){Yb(j,a)};bc=function(){return l.getObject()};cc=function(a){Yb(l,a)};dc=function(){return m.getObject()};fc=function(){Yb(m,c())};gc=function(){return q.getObject()};hc=function(a){Yb(q,a)};ic=function(){return o.getObject()};
jc=function(a){Yb(o,a)};var j=new U(0,600);j.j=a;var l=new U(0,600);l.j=b;var m=new U(0,600);m.j=c;var q=new U(0,600);q.j=d;var o=new U(0,600);o.j=f}else $b=a,ac=p,bc=b,cc=p,dc=c,fc=p,gc=d,hc=p,ic=f,jc=p})();var V={},W={},X={},Y={};
function kc(a,b,c,d,f){if(b)if(ca(b))for(var e=0;e<b.length;e++)kc(a,b[e],c,d,f);else{var d=!!d,g=W;b in g||(g[b]=$b());g=g[b];d in g||(g[d]=$b(),g.g++);var g=g[d],j=ga(a),l;g.f++;if(g[j]){l=g[j];for(e=0;e<l.length;e++)if(g=l[e],g.v==c&&g.U==f){if(g.s)break;return}}else l=g[j]=bc(),g.g++;e=dc();e.src=a;g=gc();g.D(c,e,a,b,d,f);c=g.key;e.key=c;l.push(g);V[c]=g;X[j]||(X[j]=bc());X[j].push(g);a.addEventListener?(a==n||!a.ea)&&a.addEventListener(b,e,d):a.attachEvent(b in Y?Y[b]:Y[b]="on"+b,e)}else throw Error("Invalid event type");
}function lc(a,b,c,d,f){if(ca(b))for(var e=0;e<b.length;e++)lc(a,b[e],c,d,f);else{d=!!d;a:{e=W;if(b in e&&(e=e[b],d in e&&(e=e[d],a=ga(a),e[a]))){a=e[a];break a}a=i}if(a)for(e=0;e<a.length;e++)if(a[e].v==c&&a[e].capture==d&&a[e].U==f){mc(a[e].key);break}}}
function mc(a){if(V[a]){var b=V[a];if(!b.s){var c=b.src,d=b.type,f=b.ra,e=b.capture;c.removeEventListener?(c==n||!c.ea)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in Y?Y[d]:Y[d]="on"+d,f);c=ga(c);f=W[d][e][c];if(X[c]){var g=X[c],j=z(g,b);j>=0&&y.splice.call(g,j,1);g.length==0&&delete X[c]}b.s=!0;f.oa=!0;nc(d,e,c,f);delete V[a]}}}
function nc(a,b,c,d){if(!d.H&&d.oa){for(var f=0,e=0;f<d.length;f++)if(d[f].s){var g=d[f].ra;g.src=i;fc(g);hc(d[f])}else f!=e&&(d[e]=d[f]),e++;d.length=e;d.oa=!1;e==0&&(cc(d),delete W[a][b][c],W[a][b].g--,W[a][b].g==0&&(ac(W[a][b]),delete W[a][b],W[a].g--),W[a].g==0&&(ac(W[a]),delete W[a]))}}
function oc(a){var b,c=0,d=b==i;b=!!b;if(a==i)wa(X,function(a){for(var e=a.length-1;e>=0;e--){var f=a[e];if(d||b==f.capture)mc(f.key),c++}});else if(a=ga(a),X[a])for(var a=X[a],f=a.length-1;f>=0;f--){var e=a[f];if(d||b==e.capture)mc(e.key),c++}}function pc(a,b,c,d,f){var e=1,b=ga(b);if(a[b]){a.f--;a=a[b];a.H?a.H++:a.H=1;try{for(var g=a.length,j=0;j<g;j++){var l=a[j];l&&!l.s&&(e&=qc(l,f)!==!1)}}finally{a.H--,nc(c,d,b,a)}}return Boolean(e)}
function qc(a,b){var c=a.handleEvent(b);a.aa&&mc(a.key);return c}
ec(function(a,b){if(!V[a])return!0;var c=V[a],d=c.type,f=W;if(!(d in f))return!0;var f=f[d],e,g;Ob===h&&(Ob=x&&!n.addEventListener);if(Ob){e=b||aa("window.event");var j=!0 in f,l=!1 in f;if(j){if(e.keyCode<0||e.returnValue!=h)return!0;a:{var m=!1;if(e.keyCode==0)try{e.keyCode=-1;break a}catch(q){m=!0}if(m||e.returnValue==h)e.returnValue=!0}}m=ic();m.D(e,this);e=!0;try{if(j){for(var o=bc(),v=m.currentTarget;v;v=v.parentNode)o.push(v);g=f[!0];g.f=g.g;for(var w=o.length-1;!m.n&&w>=0&&g.f;w--)m.currentTarget=
o[w],e&=pc(g,o[w],d,!0,m);if(l){g=f[!1];g.f=g.g;for(w=0;!m.n&&w<o.length&&g.f;w++)m.currentTarget=o[w],e&=pc(g,o[w],d,!1,m)}}else e=qc(c,m)}finally{if(o)o.length=0,cc(o);m.q();jc(m)}return e}d=new T(b,this);try{e=qc(c,d)}finally{d.q()}return e});function rc(){}t(rc,R);k=rc.prototype;k.ea=!0;k.Y=i;k.addEventListener=function(a,b,c,d){kc(this,a,b,c,d)};k.removeEventListener=function(a,b,c,d){lc(this,a,b,c,d)};
k.dispatchEvent=function(a){var b=a.type||a,c=W;if(b in c){if(r(a))a=new S(a,this);else if(a instanceof S)a.target=a.target||this;else{var d=a,a=new S(b,this);ya(a,d)}var d=1,f,c=c[b],b=!0 in c,e;if(b){f=[];for(e=this;e;e=e.Y)f.push(e);e=c[!0];e.f=e.g;for(var g=f.length-1;!a.n&&g>=0&&e.f;g--)a.currentTarget=f[g],d&=pc(e,f[g],a.type,!0,a)&&a.z!=!1}if(!1 in c)if(e=c[!1],e.f=e.g,b)for(g=0;!a.n&&g<f.length&&e.f;g++)a.currentTarget=f[g],d&=pc(e,f[g],a.type,!1,a)&&a.z!=!1;else for(f=this;!a.n&&f&&e.f;f=
f.Y)a.currentTarget=f,d&=pc(e,f,a.type,!1,a)&&a.z!=!1;a=Boolean(d)}else a=!0;return a};k.h=function(){rc.o.h.call(this);oc(this);this.Y=i};function Z(a,b,c,d,f){function e(a){if(a)a.tabIndex=0,kc(a,Pb,g.Ia,!1,g),kc(a,Qb,g.Ja,!1,g)}this.N=f||Fb();this.k=(r(a)?this.N.a.getElementById(a):a)||i;this.t=r(d||i)?this.N.a.getElementById(d||i):d||i;this.O=(this.W=ea(b)?b:i)||!b?i:r(b)?this.N.a.getElementById(b):b;this.C=c==!0;var g=this;e(this.k);e(this.t);sc(this,this.C)}t(Z,rc);Z.prototype.h=function(){this.k&&oc(this.k);this.t&&oc(this.t);Z.o.h.call(this)};Z.prototype.toggle=function(){sc(this,!this.C)};
function sc(a,b){if(a.O)Lb(a.O,b);else if(b&&a.W)a.O=a.W();if(a.t)Lb(a.k,!b),Lb(a.t,b);else{if(a.k){var c=a.k;b?Cb(c,"goog-zippy-expanded"):Db(c,"goog-zippy-expanded");c=a.k;!b?Cb(c,"goog-zippy-collapsed"):Db(c,"goog-zippy-collapsed")}a.k&&a.k.setAttribute("aria-expanded",b)}a.C=b;a.dispatchEvent(new tc("toggle",a,a.C))}Z.prototype.Ja=function(a){if(a.keyCode==13||a.keyCode==32)this.toggle(),a.preventDefault(),a.stopPropagation()};Z.prototype.Ia=function(){this.toggle()};
function tc(a,b,c){S.call(this,a,b);this.Sa=c}t(tc,S);function uc(a,b){this.ta=a;this.c=b||Fb();var c=s(this.Ka,this);a.pa.push(c)}var Nb,vc=".goog-tweak-root{background:#ffc; padding:0 4px}";x||(vc+=".goog-inline-block{display:inline-block}");Na&&(vc+=".goog-tweak-root,.goog-tweak-root fieldset{line-height:2em;}");Nb=vc;function wc(a,b){return A(a instanceof $,b instanceof $)||A(a instanceof N,b instanceof N)||A(a instanceof tb,b instanceof tb)||A(a.label,b.label)||A(a.e,b.e)}
function xc(a){var a=a.A,b=[],c=0,d;for(d in a)b[c++]=a[d];b.sort(wc);return b}function yc(a){var b=a.label;b==a.e&&(b=b.substr(b.lastIndexOf(".")+1));return b}uc.prototype.T=function(){return this.Q.T()};uc.prototype.Na=function(){var a=wb(this.ta),b=this.c.a.parentWindow||this.c.a.defaultView;a!=b.location.search?b.location.search=a:b.location.reload()};
uc.prototype.J=function(){var a=this.c.a;if(!("__closure_tweak_installed_"in a)){var b=Fb(a),c=i;if(x)c=b.a.createStyleSheet(),Mb(c);else{var d=Gb(b.a,"head",h,h)[0];d||(c=Gb(b.a,"body",h,h)[0],d=b.b("head"),c.parentNode.insertBefore(d,c));c=b.b("style");Mb(c);b.appendChild(d,c)}a.__closure_tweak_installed_=!0}b=this.c;a=b.b("button",{style:"font-weight:bold"},"Apply Tweaks");a.onclick=s(this.Na,this);b=new zc([],b);a=b.J(a);a.className+=" goog-tweak-root";this.Q=b;b=vb(this.ta,!1);for(d=0;c=b[d];d++)Ac(this,
c);return a};uc.prototype.Ka=function(a){this.Q&&Ac(this,a)};function Ac(a,b){var c=a.Q,d;if(d=(d=/.+(?=\.)/.exec(b.e))?d[0]:""){var f=c.L[Bc+d];f?c=f:b=new $(d,[b])}b instanceof M&&(c=c.L[b.Ea.e]);d=b;for(var f=c.R,e=wc||A,g=0,j=f.length,l;g<j;){var m=g+j>>1,q;q=e(d,f[m]);q>0?g=m+1:(j=m,l=!q)}l=-(l?g:~g)-1;db(c.R,l,0,d);c.ma.insertBefore(Cc(c,d),c.ma.childNodes[l]||i)}
function zc(a,b){this.R=a;this.za=function(){var a=this.parentNode,b=!a.style.display;Lb(a.lastChild.lastChild,b);a.style.display=b?"block":""};this.c=b||Fb();this.L={}}zc.prototype.T=function(){return this.va};
zc.prototype.J=function(a){var b=this.c,c=this.R,d=b.b("div"),f=b.b("a",{href:"javascript:;",onclick:s(this.Qa,this)},"Toggle all Descriptions");d.appendChild(f);this.ma=b=b.createElement("div");for(var f=0,e;e=c[f];f++)b.appendChild(Cc(this,e));a&&b.appendChild(a);d.appendChild(b);return this.va=d};
function Cc(a,b){var c=a.c,d=b instanceof $||b instanceof N;return c.b("div",d?"goog-tweak-entry":"goog-tweak-entry goog-inline-block",c.b(d?"span":"label",{title:b.description,style:"color:"+(b.w?"":"blue")},Dc(a,b)),Ec(a,b))}
function Ec(a,b){var c=a.c.createElement("span");c.innerHTML='<b style="padding:0 1em 0 .5em">?</b><span style="display:none;color:#666"></span>';c.onclick=a.za;var d=c.lastChild;Kb(d,b.description);b.w||(d.innerHTML+=' <span style="color:blue">(no restart required)</span>');return c}zc.prototype.Qa=function(){var a=!this.Pa;this.Pa=a;for(var b=Gb(this.c.a,"div","goog-tweak-entry",this.va),c=0,d;d=b[c];c++){var f=a;Lb(d.lastChild.lastChild,f);d.style.display=f?"block":""}};
function Fc(a,b,c,d){var a=a.c,f=a.a.createDocumentFragment();f.appendChild(a.createTextNode(c+": "));for(var e=a.createElement("select"),c=b.p,g=0,j=c.length;g<j;++g){var l=a.createElement("option");l.text=String(c[g]);l.value=String(c[g]);e.appendChild(l)}f.appendChild(e);e.value=H(b);e.onchange=d;rb(b,function(){e.value=H(b)});return f}
function Gc(a,b,c){var a=a.c,d=a.a.createDocumentFragment(),f=a.b("input",{type:"checkbox"});d.appendChild(f);d.appendChild(a.createTextNode(c));f.defaultChecked=H(b);f.checked=H(b);f.onchange=function(){I(b,f.checked)};rb(b,function(){f.checked=H(b)});return d}
function Hc(a,b,c,d){var f=a.c,e=f.b("a",{href:"javascript:;"},c+" \u00bb"),c=f.b("a",{href:"javascript:;"},"\u00ab "+c);c.style.marginRight="10px";d=new zc(d,f);a.L[b.e]=d;a=d.J();a=f.b("fieldset","goog-inline-block",f.b("legend",i,c,a.firstChild),a);new Z(e,a,!1,c);f=f.a.createDocumentFragment();f.appendChild(e);f.appendChild(a);return f}
function Ic(a,b,c,d){var a=a.c,f=a.a.createDocumentFragment();f.appendChild(a.createTextNode(c+": "));var e=a.b("input",{value:H(b),size:5,onblur:d});f.appendChild(e);rb(b,function(){e.value=H(b)});return f}
function Dc(a,b){var c=yc(b);if(b instanceof L)return Gc(a,b,c);else if(b instanceof N){var d=xc(b);return Hc(a,b,c,d)}else if(b instanceof J)return d=function(){I(b,this.value)},b.p?Fc(a,b,c,d):Ic(a,b,c,d);else if(b instanceof K)return d=function(){isNaN(this.value)?this.value=H(b):I(b,+this.value)},b.p?Fc(a,b,c,d):Ic(a,b,c,d);else if(b instanceof $)return Hc(a,b,b.label,b.Ca);return a.c.b("button",{onclick:s(b.ja,b)},c)}
function $(a,b){E.call(this,Bc+a,"Tweaks within the "+a+" namespace.");this.Ca=b;this.label=a}t($,E);var Bc="!";zb("Checkbox","boolean\u5024\u306f\u30c1\u30a7\u30c3\u30af\u30dc\u30c3\u30af\u30b9\u3068\u3057\u3066\u8868\u793a\u3055\u308c\u307e\u3059");zb("CheckedCheckbox","boolean\u5024\u306e\u30c7\u30d5\u30a9\u30eb\u30c8\u306ffalse\u3067\u3059\u304c\u3001\u5909\u66f4\u53ef\u80fd\u3067\u3059",!0);P(new J("Textbox","\u6587\u5b57\u5217\u306f\u30c6\u30ad\u30b9\u30c8\u30dc\u30c3\u30af\u30b9\u3068\u3057\u3066\u8868\u793a\u3055\u308c\u307e\u3059"),h,h);
P(new J("TextboxWithText","\u6587\u5b57\u5217\u306e\u30c7\u30d5\u30a9\u30eb\u30c8\u306f\u7a7a\u6587\u5b57\u5217\u3067\u3059\u304c\u3001\u5909\u66f4\u53ef\u80fd\u3067\u3059"),"Default text",h);P(new J("Combobox","validValues\u30aa\u30d7\u30b7\u30e7\u30f3\u3092\u4ed8\u3051\u305f\u6587\u5b57\u5217\u306f\u3001\u30c9\u30ed\u30c3\u30d7\u30c0\u30a6\u30f3\u306b\u306a\u308a\u307e\u3059"),"",{K:["Item1","Item2","Item3"]});
P(new K("Numberbox","\u6570\u5024\u306f\u30c6\u30ad\u30b9\u30c8\u30dc\u30c3\u30af\u30b9\u3068\u3057\u3066\u8868\u793a\u3055\u308c\u307e\u3059"),h,h);P(new K("NumberboxWithDefault","\u6570\u5024\u306e\u30c7\u30d5\u30a9\u30eb\u30c8\u306f0\u3067\u3059\u304c\u3001\u5909\u66f4\u53ef\u80fd\u3067\u3059"),100,h);
P(new K("NumberConbobox","validValues\u30aa\u30d7\u30b7\u30e7\u30f3\u3092\u4ed8\u3051\u305f\u6570\u5024\u306f\u3001\u30c9\u30ed\u30c3\u30d7\u30c0\u30a6\u30f3\u306b\u306a\u308a\u307e\u3059"),0,{K:[0,5,10,50]});var Jc=new N("BooleanGroup","Boolean\u5024\u306f\u30b0\u30eb\u30fc\u30d7\u5316\u3067\u304d\u307e\u3059");P(Jc,h,h);O=Jc;zb("GroupItem1","Group item 1");zb("GroupItem2","Group item 2");
var O=i,Kc=new tb("Button","\u4efb\u610f\u306e\u64cd\u4f5c\u3092\u884c\u3046\u30dc\u30bf\u30f3\u3082\u8ffd\u52a0\u3067\u304d\u307e\u3059",function(){alert("clicked!")});Kc.label=Kc.label;P(Kc);new function(){Kb(r("url")?document.getElementById("url"):"url",location.href);var a;(a=yb())?(a=new uc(a,h),a.J(),a=a.T()):a=h;a?(r("my-tweak-ui")?document.getElementById("my-tweak-ui"):"my-tweak-ui").appendChild(a):Kb(r("my-tweak-ui")?document.getElementById("my-tweak-ui"):"my-tweak-ui","STRIPPED!")};})();
