(function(){var h=void 0,i=true,j=null,k=false,m,p=this;function aa(a){for(var a=a.split("."),b=p,c;c=a.shift();)if(b[c]!=j)b=b[c];else return j;return b}
function ba(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function r(a){return ba(a)=="array"}function ca(a){var b=ba(a);return b=="array"||b=="object"&&typeof a.length=="number"}function s(a){return typeof a=="string"}function da(a){return ba(a)=="function"}function ea(a){a=ba(a);return a=="object"||a=="array"||a=="function"}function fa(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ha=0;
function ia(a,b,c){return a.call.apply(a.bind,arguments)}function ka(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ia:ka;return u.apply(j,arguments)}var la=Date.now||function(){return+new Date};
function v(a,b){function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c};var ma=/^[a-zA-Z0-9\-_.!~*'()]*$/;function na(a){a=String(a);return!ma.test(a)?encodeURIComponent(a):a}function oa(a){if(!pa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(qa,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(ra,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(sa,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(ta,"&quot;"));return a}var qa=/&/g,ra=/</g,sa=/>/g,ta=/\"/g,pa=/[&<>\"]/;function ua(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};function va(a,b){for(var c in a)b.call(h,a[c],c,a)}var wa="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function xa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<wa.length;e++)c=wa[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function ya(a){for(var b=[],c=0;c<a.length;c+=2){var d=a[c],f=a[c+1],e=b;if(r(f))for(var g=0;g<f.length;g++)e.push("&",d),f[g]!==""&&e.push("=",na(f[g]));else f!=j&&(e.push("&",d),f!==""&&e.push("=",na(f)))}b[0]="";return b.join("")}function za(a,b,c,d){for(var f=c.length;(b=a.indexOf(c,b))>=0&&b<d;){var e=a.charCodeAt(b-1);if(e==38||e==63)if(e=a.charCodeAt(b+f),!e||e==61||e==38||e==35)return b;b+=f+1}return-1}var Aa=/#|$/,Ba=/[?&]($|#)/;
function Ca(a,b){for(var c=a.search(Aa),d=0,f,e=[];(f=za(a,d,b,c))>=0;)e.push(a.substring(d,f)),d=Math.min(a.indexOf("&",f)+1||c,c);e.push(a.substr(d));return e.join("").replace(Ba,"$1")};var w,Da,Ea,Fa,Ga;function Ha(){return p.navigator?p.navigator.userAgent:j}Ga=Fa=Ea=Da=w=k;var Ia;if(Ia=Ha()){var Ja=p.navigator;w=Ia.indexOf("Opera")==0;Da=!w&&Ia.indexOf("MSIE")!=-1;Fa=(Ea=!w&&Ia.indexOf("WebKit")!=-1)&&Ia.indexOf("Mobile")!=-1;Ga=!w&&!Ea&&Ja.product=="Gecko"}var Ka=w,y=Da,z=Ga,A=Ea,La=Fa,Ma=p.navigator,Na=(Ma&&Ma.platform||"").indexOf("Mac")!=-1,Oa;
a:{var Pa="",Qa;if(Ka&&p.opera)var Ra=p.opera.version,Pa=typeof Ra=="function"?Ra():Ra;else if(z?Qa=/rv\:([^\);]+)(\)|;)/:y?Qa=/MSIE\s+([^\);]+)(\)|;)/:A&&(Qa=/WebKit\/(\S+)/),Qa)var Sa=Qa.exec(Ha()),Pa=Sa?Sa[1]:"";if(y){var Ta,Ua=p.document;Ta=Ua?Ua.documentMode:h;if(Ta>parseFloat(Pa)){Oa=String(Ta);break a}}Oa=Pa}var Va={};
function B(a){var b;if(!(b=Va[a])){b=0;for(var c=String(Oa).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;b==0&&e<f;e++){var g=c[e]||"",l=d[e]||"",n=RegExp("(\\d*)(\\D*)","g"),o=RegExp("(\\d*)(\\D*)","g");do{var t=n.exec(g)||["","",""],q=o.exec(l)||["","",""];if(t[0].length==0&&q[0].length==0)break;b=ua(t[1].length==0?0:parseInt(t[1],10),q[1].length==0?0:parseInt(q[1],10))||ua(t[2].length==0,q[2].length==
0)||ua(t[2],q[2])}while(b==0)}b=Va[a]=b>=0}return b}var Wa={};function Xa(){return Wa[9]||(Wa[9]=y&&document.documentMode&&document.documentMode>=9)};var C=Array.prototype,D=C.indexOf?function(a,b,c){return C.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:c<0?Math.max(0,a.length+c):c;if(s(a))return!s(b)||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ya=C.forEach?function(a,b,c){C.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=s(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function Za(a){return C.concat.apply(C,arguments)}
function $a(a){if(r(a))return Za(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function ab(a,b,c,d){C.splice.apply(a,bb(arguments,1))}function bb(a,b,c){return arguments.length<=2?C.slice.call(a,b):C.slice.call(a,b,c)}function E(a,b){return a>b?1:a<b?-1:0};function cb(a){return db(a||arguments.callee.caller,[])}
function db(a,b){var c=[];if(D(b,a)>=0)c.push("[...circular reference...]");else if(a&&b.length<50){c.push(eb(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){f>0&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=eb(e))?e:"[fn]";break;default:e=typeof e}e.length>40&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(db(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function eb(a){if(fb[a])return fb[a];a=String(a);if(!fb[a]){var b=/function ([^\(]+)/.exec(a);fb[a]=b?b[1]:"[Anonymous]"}return fb[a]}var fb={};function F(a,b,c,d,f){this.reset(a,b,c,d,f)}F.prototype.Oa=0;F.prototype.ga=j;F.prototype.fa=j;var gb=0;F.prototype.reset=function(a,b,c,d,f){this.Oa=typeof f=="number"?f:gb++;this.Wa=d||la();this.r=a;this.Ga=b;this.Ua=c;delete this.ga;delete this.fa};F.prototype.va=function(a){this.r=a};function G(a){this.Ha=a}G.prototype.G=j;G.prototype.r=j;G.prototype.K=j;G.prototype.ia=j;function hb(a,b){this.name=a;this.value=b}hb.prototype.toString=function(){return this.name};var ib=new hb("WARNING",900),jb=new hb("CONFIG",700);G.prototype.getParent=function(){return this.G};G.prototype.va=function(a){this.r=a};function kb(a){return a.r?a.r:a.G?kb(a.G):j}
G.prototype.log=function(a,b,c){if(a.value>=kb(this).value){a=this.Ca(a,b,c);b="log:"+a.Ga;p.console&&(p.console.timeStamp?p.console.timeStamp(b):p.console.markTimeline&&p.console.markTimeline(b));p.msWriteProfilerMark&&p.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.ia)for(var f=0,e=h;e=c.ia[f];f++)e(d);b=b.getParent()}}};
G.prototype.Ca=function(a,b,c){var d=new F(a,String(b),this.Ha);if(c){d.ga=c;var f;var e=arguments.callee.caller;try{var g;var l=aa("window.location.href");if(s(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:l,stack:"Not available"};else{var n,o,t=k;try{n=c.lineNumber||c.Ta||"Not available"}catch(q){n="Not available",t=i}try{o=c.fileName||c.filename||c.sourceURL||l}catch(ja){o="Not available",t=i}g=t||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:n,
fileName:o,stack:c.stack||"Not available"}:c}f="Message: "+oa(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+oa(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+oa(cb(e)+"-> ")}catch(x){f="Exception trying to expose exception! You win, we lose. "+x}d.fa=f}return d};function lb(a,b){a.log(ib,b,h)}var mb={},nb=j;
function H(a){nb||(nb=new G(""),mb[""]=nb,nb.va(jb));var b;if(!(b=mb[a])){b=new G(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=H(a.substr(0,c));if(!c.K)c.K={};c.K[d]=b;b.G=c;mb[a]=b}return b};function I(a,b){this.label=this.e=a;this.description=b;this.ba=[]}I.prototype.i=H("goog.tweak.BaseEntry");I.prototype.t=i;function ob(a,b){a.ba.push(b)}I.prototype.ha=function(){for(var a=0,b;b=this.ba[a];++a)b(this)};function J(a,b){I.call(this,a,b);this.j=this.e.toLowerCase()}v(J,I);J.prototype.i=H("goog.tweak.BaseSetting");J.prototype.D=0;J.prototype.Y=function(a){this.j=a};function pb(a){if(a.D==0)a.D=1,a.C(a.T==h?j:a.T),a.D=2}function K(a,b,c){J.call(this,a,b);this.d=c}v(K,J);K.prototype.i=H("goog.tweak.BasePrimitiveSetting");
function L(a){pb(a);return a.W}function M(a,b){pb(a);var c=a.W!=b;a.W=b;if(a.D==1)a.Ra=b;else{if(!a.t)a.Ra=b;c&&a.ha()}}K.prototype.Q=function(){pb(this);return this.W==this.d?j:this.N()};function N(a,b){K.call(this,a,b,"")}v(N,K);N.prototype.i=H("goog.tweak.StringSetting");N.prototype.N=function(){return L(this)};N.prototype.wa=function(a){if((this.m=a)&&!(D(a,this.d)>=0))this.d=a[0]};
N.prototype.C=function(a){if(a==j)M(this,this.d);else{var b=this.m;if(b){for(var a=a.toLowerCase(),c=0,d=b.length;c<d;++c)if(a==b[c].toLowerCase()){M(this,b[c]);return}lb(this.i,"Tweak "+this.e+" has value outside of expected range:"+a)}M(this,a)}};function O(a,b){K.call(this,a,b,0)}v(O,K);O.prototype.i=H("goog.tweak.NumericSetting");O.prototype.N=function(){return""+L(this)};O.prototype.wa=function(a){if((this.m=a)&&!(D(a,this.d)>=0))this.d=a[0]};
O.prototype.C=function(a){if(a==j)M(this,this.d);else{var b=+a;this.m&&!(D(this.m,b)>=0)&&lb(this.i,"Tweak "+this.e+" has value outside of expected range: "+a);isNaN(b)?(lb(this.i,"Tweak "+this.e+" has value of NaN, resetting to "+this.d),M(this,this.d)):M(this,b)}};function P(a,b){K.call(this,a,b,k)}v(P,K);P.prototype.i=H("goog.tweak.BooleanSetting");P.prototype.N=function(){return L(this)?"1":"0"};P.prototype.C=function(a){a==j?M(this,this.d):(a=a.toLowerCase(),M(this,a=="true"||a=="1"))};
function Q(a,b,c){P.call(this,a,b);this.Z=this.e.toLowerCase();this.Da=c;Q.l.Y.call(this,j)}v(Q,P);Q.prototype.i=H("goog.tweak.BooleanInGroupSetting");Q.prototype.Y=function(){};function R(a,b){J.call(this,a,b);this.w={};this.ra={}}v(R,J);R.prototype.i=H("goog.tweak.BooleanGroup");R.prototype.C=function(a){var b={};if(a)for(var a=a.split(/\s*,\s*/),c=0;c<a.length;++c){var d=a[c].toLowerCase(),f=d.charAt(0)=="-";f&&(d=d.substr(1));b[d]=!f}this.ra=b};
R.prototype.Q=function(){pb(this);var a=[],b=this.w,c=[],d=0,f;for(f in b)c[d++]=f;c.sort();for(b=0;d=this.w[c[b]];++b)d.Q()!=j&&a.push((L(d)?"":"-")+d.Z);return a.length?a.join(","):j};function qb(a,b,c){I.call(this,a,b);ob(this,c);this.t=k}v(qb,I);function rb(a,b){this.z={};for(var c=a.substr(1).split("&"),d={},f=0,e=c.length;f<e;++f){var g=c[f].split("=");g[0]&&(d[decodeURIComponent(g[0].replace(/\+/g," ")).toLowerCase()]=decodeURIComponent((g[1]||"").replace(/\+/g," ")))}this.La=d;this.oa=[];this.ca=b;this.za={}}rb.prototype.Fa=H("goog.tweak.Registry");function sb(a,b){var c=[],d;for(d in a.z){var f=a.z[d];if(f instanceof J){if(!f.j)continue}else if(b)continue;c.push(f)}return c}
function tb(a){var b=window.location.search,a=sb(a,i);a.sort(function(a,b){return E(a.j,b.j)});for(var c=[],d=0,f;f=a[d];++d){var e=f.Q();e!=j&&c.push(f.j,e);b=Ca(b,encodeURIComponent(f.j))}a=ya(c);a=a.replace(/%2C/g,",").replace(/%20/g,"+");return!a?b:b?b+"&"+a:"?"+a};var ub=j,S=j;function vb(){ub||(ub=new rb(window.location.search,{}));return ub}
function T(a,b,c){if(c){if(c.label)a.label=c.label,delete c.label;c.I&&(a.wa(c.I),delete c.I);c.pa!==h&&(a.Y(c.pa),delete c.pa);if(c.ta!==h)a.t=c.ta,delete c.ta;c.aa&&(ob(a,c.aa),delete c.aa);if(c.xa)a.Z=c.xa,delete c.xa;for(var d in c);}if(b!=h)a.d=b;if(S&&(b=S,pb(b),c=a.Z.toLowerCase(),b.w[c]=a,b=b.ra[c],b!=h))a.T=b?"1":"0";b=vb();c=a.e;if((d=b.z[c])&&d==a)lb(b.Fa,"Tweak entry registered twice: "+c);else{d=c in b.ca?b.ca[c]:b.za[c];if(d!==h)a.d=d;if(a instanceof J&&a.j)a.T=b.La[a.j];b.z[c]=a;for(c=
0;d=b.oa[c];++c)d(a)}}function wb(a,b,c){a=S?new Q(a,b,S):new P(a,b);T(a,c,h)};var xb;function yb(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function zb(a,b){var c=yb(a),d=bb(arguments,1),f;f=c;for(var e=0,g=0;g<d.length;g++)D(f,d[g])>=0||(f.push(d[g]),e++);f=e==d.length;a.className=c.join(" ");return f}function Ab(a,b){for(var c=yb(a),d=bb(arguments,1),f=c,e=0,g=0;g<f.length;g++)D(d,f[g])>=0&&(ab(f,g--,1),e++);a.className=c.join(" ")};var Bb=!y||Xa();!z&&!y||y&&Xa()||z&&B("1.9.1");y&&B("9");function Cb(a){return a?new U(a.nodeType==9?a:a.ownerDocument||a.document):xb||(xb=new U)}
function Db(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(!A||document.compatMode=="CSS1Compat"||B("528"))&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName)if(a=a.getElementsByClassName(c),b){for(var d={},f=0,e=0,g;g=a[e];e++)b==g.nodeName&&(d[f++]=g);d.length=f;return d}else return a;a=a.getElementsByTagName(b||"*");if(c){d={};for(e=f=0;g=a[e];e++)b=g.className,typeof b.split=="function"&&D(b.split(/\s+/),c)>=0&&(d[f++]=g);
d.length=f;return d}else return a}function Eb(a,b){va(b,function(b,d){d=="style"?a.style.cssText=b:d=="class"?a.className=b:d=="for"?a.htmlFor=b:d in Fb?a.setAttribute(Fb[d],b):d.lastIndexOf("aria-",0)==0?a.setAttribute(d,b):a[d]=b})}var Fb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function Gb(a,b,c){function d(c){c&&b.appendChild(s(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];if(ca(e)&&!(ea(e)&&e.nodeType>0)){var g;a:{if(e&&typeof e.length=="number")if(ea(e)){g=typeof e.item=="function"||typeof e.item=="string";break a}else if(da(e)){g=typeof e.item=="function";break a}g=k}Ya(g?$a(e):e,d)}else d(e)}}
function Hb(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild((a.nodeType==9?a:a.ownerDocument||a.document).createTextNode(b))}}function U(a){this.b=a||p.document||document}
U.prototype.a=function(a,b,c){var d=this.b,f=arguments,e=f[0],g=f[1];if(!Bb&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',oa(g.name),'"');if(g.type){e.push(' type="',oa(g.type),'"');var l={};xa(l,g);g=l;delete g.type}e.push(">");e=e.join("")}e=d.createElement(e);if(g)s(g)?e.className=g:r(g)?zb.apply(j,[e].concat(g)):Eb(e,g);f.length>2&&Gb(d,e,f);return e};U.prototype.createElement=function(a){return this.b.createElement(a)};U.prototype.createTextNode=function(a){return this.b.createTextNode(a)};
U.prototype.appendChild=function(a,b){a.appendChild(b)};function Ib(a,b){a.style.display=b?"":"none"}function Jb(a){var b=Kb;y?a.cssText=b:a[A?"innerText":"innerHTML"]=b};function Lb(){}var Mb=0;m=Lb.prototype;m.key=0;m.p=k;m.$=k;m.B=function(a,b,c,d,f,e){if(da(a))this.ja=i;else if(a&&a.handleEvent&&da(a.handleEvent))this.ja=k;else throw Error("Invalid listener argument");this.s=a;this.qa=b;this.src=c;this.type=d;this.capture=!!f;this.S=e;this.$=k;this.key=++Mb;this.p=k};m.handleEvent=function(a){return this.ja?this.s.call(this.S||this.src,a):this.s.handleEvent.call(this.s,a)};!y||Xa();var Nb=!y||Xa(),Ob=y&&!B("8");!A||B("528");z&&B("1.9b")||y&&B("8")||Ka&&B("9.5")||A&&B("528");!z||B("8");function V(){}V.prototype.ea=k;V.prototype.v=function(){if(!this.ea)this.ea=i,this.h()};V.prototype.h=function(){this.Aa&&Pb.apply(j,this.Aa)};function Qb(a){a&&typeof a.v=="function"&&a.v()}function Pb(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ca(d)?Pb.apply(j,d):Qb(d)}};function W(a,b){this.type=a;this.currentTarget=this.target=b}v(W,V);m=W.prototype;m.h=function(){delete this.type;delete this.target;delete this.currentTarget};m.k=k;m.u=i;m.stopPropagation=function(){this.k=i};m.preventDefault=function(){this.u=k};function Rb(a){Rb[" "](a);return a}Rb[" "]=function(){};function X(a,b){a&&this.B(a,b)}v(X,W);m=X.prototype;m.target=j;m.relatedTarget=j;m.offsetX=0;m.offsetY=0;m.clientX=0;m.clientY=0;m.screenX=0;m.screenY=0;m.button=0;m.keyCode=0;m.charCode=0;m.ctrlKey=k;m.altKey=k;m.shiftKey=k;m.metaKey=k;m.Ma=k;m.o=j;
m.B=function(a,b){var c=this.type=a.type;W.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(z){var f;a:{try{Rb(d.nodeName);f=i;break a}catch(e){}f=k}f||(d=j)}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=A||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=A||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Ma=Na?a.metaKey:a.ctrlKey;this.state=a.state;this.o=a;delete this.u;delete this.k};m.stopPropagation=function(){X.l.stopPropagation.call(this);this.o.stopPropagation?this.o.stopPropagation():this.o.cancelBubble=i};
m.preventDefault=function(){X.l.preventDefault.call(this);var a=this.o;if(a.preventDefault)a.preventDefault();else if(a.returnValue=k,Ob)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};m.h=function(){X.l.h.call(this);this.relatedTarget=this.currentTarget=this.target=this.o=j};var Sb={},Y={},Z={},Tb={};
function Ub(a,b,c,d,f){if(b)if(r(b)){for(var e=0;e<b.length;e++)Ub(a,b[e],c,d,f);return j}else{var d=!!d,g=Y;b in g||(g[b]={g:0,f:0});g=g[b];d in g||(g[d]={g:0,f:0},g.g++);var g=g[d],l=fa(a),n;g.f++;if(g[l]){n=g[l];for(e=0;e<n.length;e++)if(g=n[e],g.s==c&&g.S==f){if(g.p)break;return n[e].key}}else n=g[l]=[],g.g++;e=Vb();e.src=a;g=new Lb;g.B(c,e,a,b,d,f);c=g.key;e.key=c;n.push(g);Sb[c]=g;Z[l]||(Z[l]=[]);Z[l].push(g);a.addEventListener?(a==p||!a.da)&&a.addEventListener(b,e,d):a.attachEvent(b in Tb?
Tb[b]:Tb[b]="on"+b,e);return c}else throw Error("Invalid event type");}function Vb(){var a=Wb,b=Nb?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}function Xb(a,b,c,d,f){if(r(b))for(var e=0;e<b.length;e++)Xb(a,b[e],c,d,f);else{d=!!d;a:{e=Y;if(b in e&&(e=e[b],d in e&&(e=e[d],a=fa(a),e[a]))){a=e[a];break a}a=j}if(a)for(e=0;e<a.length;e++)if(a[e].s==c&&a[e].capture==d&&a[e].S==f){Yb(a[e].key);break}}}
function Yb(a){if(!Sb[a])return k;var b=Sb[a];if(b.p)return k;var c=b.src,d=b.type,f=b.qa,e=b.capture;c.removeEventListener?(c==p||!c.da)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in Tb?Tb[d]:Tb[d]="on"+d,f);c=fa(c);f=Y[d][e][c];if(Z[c]){var g=Z[c],l=D(g,b);l>=0&&C.splice.call(g,l,1);g.length==0&&delete Z[c]}b.p=i;f.na=i;Zb(d,e,c,f);delete Sb[a];return i}
function Zb(a,b,c,d){if(!d.F&&d.na){for(var f=0,e=0;f<d.length;f++)d[f].p?d[f].qa.src=j:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.na=k;e==0&&(delete Y[a][b][c],Y[a][b].g--,Y[a][b].g==0&&(delete Y[a][b],Y[a].g--),Y[a].g==0&&delete Y[a])}}function $b(a){var b,c=0,d=b==j;b=!!b;if(a==j)va(Z,function(a){for(var e=a.length-1;e>=0;e--){var f=a[e];if(d||b==f.capture)Yb(f.key),c++}});else if(a=fa(a),Z[a])for(var a=Z[a],f=a.length-1;f>=0;f--){var e=a[f];if(d||b==e.capture)Yb(e.key),c++}}
function ac(a,b,c,d,f){var e=1,b=fa(b);if(a[b]){a.f--;a=a[b];a.F?a.F++:a.F=1;try{for(var g=a.length,l=0;l<g;l++){var n=a[l];n&&!n.p&&(e&=bc(n,f)!==k)}}finally{a.F--,Zb(c,d,b,a)}}return Boolean(e)}function bc(a,b){var c=a.handleEvent(b);a.$&&Yb(a.key);return c}
function Wb(a,b){if(!Sb[a])return i;var c=Sb[a],d=c.type,f=Y;if(!(d in f))return i;var f=f[d],e,g;if(!Nb){e=b||aa("window.event");var l=i in f,n=k in f;if(l){if(e.keyCode<0||e.returnValue!=h)return i;a:{var o=k;if(e.keyCode==0)try{e.keyCode=-1;break a}catch(t){o=i}if(o||e.returnValue==h)e.returnValue=i}}o=new X;o.B(e,this);e=i;try{if(l){for(var q=[],ja=o.currentTarget;ja;ja=ja.parentNode)q.push(ja);g=f[i];g.f=g.g;for(var x=q.length-1;!o.k&&x>=0&&g.f;x--)o.currentTarget=q[x],e&=ac(g,q[x],d,i,o);if(n){g=
f[k];g.f=g.g;for(x=0;!o.k&&x<q.length&&g.f;x++)o.currentTarget=q[x],e&=ac(g,q[x],d,k,o)}}else e=bc(c,o)}finally{if(q)q.length=0;o.v()}return e}d=new X(b,this);try{e=bc(c,d)}finally{d.v()}return e};function cc(a){this.Ea=a;this.U=[]}v(cc,V);var dc=[];function ec(a,b,c,d){r(c)||(dc[0]=c,c=dc);for(var f=0;f<c.length;f++)a.U.push(Ub(b,c[f],d||a,k,a.Ea||a))}cc.prototype.h=function(){cc.l.h.call(this);Ya(this.U,Yb);this.U.length=0};cc.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function fc(){}v(fc,V);m=fc.prototype;m.da=i;m.X=j;m.addEventListener=function(a,b,c,d){Ub(this,a,b,c,d)};m.removeEventListener=function(a,b,c,d){Xb(this,a,b,c,d)};
m.dispatchEvent=function(a){var b=a.type||a,c=Y;if(b in c){if(s(a))a=new W(a,this);else if(a instanceof W)a.target=a.target||this;else{var d=a,a=new W(b,this);xa(a,d)}var d=1,f,c=c[b],b=i in c,e;if(b){f=[];for(e=this;e;e=e.X)f.push(e);e=c[i];e.f=e.g;for(var g=f.length-1;!a.k&&g>=0&&e.f;g--)a.currentTarget=f[g],d&=ac(e,f[g],a.type,i,a)&&a.u!=k}if(k in c)if(e=c[k],e.f=e.g,b)for(g=0;!a.k&&g<f.length&&e.f;g++)a.currentTarget=f[g],d&=ac(e,f[g],a.type,k,a)&&a.u!=k;else for(f=this;!a.k&&f&&e.f;f=f.X)a.currentTarget=
f,d&=ac(e,f,a.type,k,a)&&a.u!=k;a=Boolean(d)}else a=i;return a};m.h=function(){fc.l.h.call(this);$b(this);this.X=j};function $(a,b,c,d,f){function e(a){if(a)a.tabIndex=0,a.setAttribute("role","tab"),a.Va="tab",zb(a,"goog-zippy-header"),a&&ec(g.ma,a,"click",g.Ia),a&&ec(g.ka,a,"keydown",g.Ja)}this.L=f||Cb();this.n=(s(a)?this.L.b.getElementById(a):a)||j;this.M=s(d||j)?this.L.b.getElementById(d||j):d||j;this.q=(this.V=da(b)?b:j)||!b?j:s(b)?this.L.b.getElementById(b):b;this.A=c==i;this.ka=new cc(this);this.ma=new cc(this);var g=this;e(this.n);e(this.M);gc(this,this.A)}v($,fc);
$.prototype.h=function(){$.l.h.call(this);Qb(this.ka);Qb(this.ma)};$.prototype.toggle=function(){gc(this,!this.A)};function gc(a,b){if(a.q)Ib(a.q,b);else if(b&&a.V)a.q=a.V();a.q&&zb(a.q,"goog-zippy-content");if(a.M)Ib(a.n,!b),Ib(a.M,b);else if(a.n){var c=a.n;b?zb(c,"goog-zippy-expanded"):Ab(c,"goog-zippy-expanded");c=a.n;!b?zb(c,"goog-zippy-collapsed"):Ab(c,"goog-zippy-collapsed");a.n.setAttribute("aria-expanded",b)}a.A=b;a.dispatchEvent(new hc("toggle",a,a.A))}
$.prototype.Ja=function(a){if(a.keyCode==13||a.keyCode==32)this.toggle(),this.dispatchEvent(new W("action",this)),a.preventDefault(),a.stopPropagation()};$.prototype.Ia=function(){this.toggle();this.dispatchEvent(new W("action",this))};function hc(a,b,c){W.call(this,a,b);this.Sa=c}v(hc,W);function ic(a,b){this.sa=a;this.c=b||Cb();var c=u(this.Ka,this);a.oa.push(c)}var Kb,jc=".goog-tweak-root{background:#ffc; padding:0 4px}";y||(jc+=".goog-inline-block{display:inline-block}");La&&(jc+=".goog-tweak-root,.goog-tweak-root fieldset{line-height:2em;}");Kb=jc;
function kc(){var a=vb();if(a){var b=Cb(),c=b.a("a",{href:"javascript:;"},"Show Tweaks"),d=b.a("a",{href:"javascript:;"},"Hide Tweaks"),f=b.a("div",j,c);new $(c,function(){var c=new ic(a,b);c.H();d.style.marginRight="10px";c=c.R();c.insertBefore(d,c.firstChild);f.appendChild(c);return c},k,d);return f}}function lc(a,b){return E(a instanceof mc,b instanceof mc)||E(a instanceof R,b instanceof R)||E(a instanceof qb,b instanceof qb)||E(a.label,b.label)||E(a.e,b.e)}
function nc(a){var a=a.w,b=[],c=0,d;for(d in a)b[c++]=a[d];b.sort(lc);return b}function oc(a){var b=a.label;b==a.e&&(b=b.substr(b.lastIndexOf(".")+1));return b}ic.prototype.R=function(){return this.O.R()};ic.prototype.Na=function(){var a=tb(this.sa),b=this.c.b.parentWindow||this.c.b.defaultView;a!=b.location.search?b.location.search=a:b.location.reload()};
ic.prototype.H=function(){var a=this.c.b;if(!("__closure_tweak_installed_"in a)){var b=Cb(a),c=j;if(y)c=b.b.createStyleSheet(),Jb(c);else{var d=Db(b.b,"head",h,h)[0];d||(c=Db(b.b,"body",h,h)[0],d=b.a("head"),c.parentNode.insertBefore(d,c));c=b.a("style");Jb(c);b.appendChild(d,c)}a.__closure_tweak_installed_=i}b=this.c;a=b.a("button",{style:"font-weight:bold"},"Apply Tweaks");a.onclick=u(this.Na,this);b=new pc([],b);a=b.H(a);a.className+=" goog-tweak-root";this.O=b;b=sb(this.sa,k);for(d=0;c=b[d];d++)qc(this,
c);return a};ic.prototype.Ka=function(a){this.O&&qc(this,a)};function qc(a,b){var c=a.O,d;if(d=(d=/.+(?=\.)/.exec(b.e))?d[0]:""){var f=c.J[rc+d];f?c=f:b=new mc(d,[b])}b instanceof Q&&(c=c.J[b.Da.e]);d=b;for(var f=c.P,e=lc||E,g=0,l=f.length,n;g<l;){var o=g+l>>1,t;t=e(d,f[o]);t>0?g=o+1:(l=o,n=!t)}n=-(n?g:~g)-1;ab(c.P,n,0,d);c.la.insertBefore(sc(c,d),c.la.childNodes[n]||j)}
function pc(a,b){this.P=a;this.ya=function(){var a=this.parentNode,b=!a.style.display;Ib(a.lastChild.lastChild,b);a.style.display=b?"block":""};this.c=b||Cb();this.J={}}pc.prototype.R=function(){return this.ua};
pc.prototype.H=function(a){var b=this.c,c=this.P,d=b.a("div"),f=b.a("a",{href:"javascript:;",onclick:u(this.Qa,this)},"Toggle all Descriptions");d.appendChild(f);this.la=b=b.createElement("div");for(var f=0,e;e=c[f];f++)b.appendChild(sc(this,e));a&&b.appendChild(a);d.appendChild(b);return this.ua=d};
function sc(a,b){var c=a.c,d=b instanceof mc||b instanceof R;return c.a("div",d?"goog-tweak-entry":"goog-tweak-entry goog-inline-block",c.a(d?"span":"label",{title:b.description,style:"color:"+(b.t?"":"blue")},tc(a,b)),uc(a,b))}
function uc(a,b){var c=a.c.createElement("span");c.innerHTML='<b style="padding:0 1em 0 .5em">?</b><span style="display:none;color:#666"></span>';c.onclick=a.ya;var d=c.lastChild;Hb(d,b.description);b.t||(d.innerHTML+=' <span style="color:blue">(no restart required)</span>');return c}pc.prototype.Qa=function(){var a=!this.Pa;this.Pa=a;for(var b=Db(this.c.b,"div","goog-tweak-entry",this.ua),c=0,d;d=b[c];c++){var f=a;Ib(d.lastChild.lastChild,f);d.style.display=f?"block":""}};
function vc(a,b,c,d){var a=a.c,f=a.b.createDocumentFragment();f.appendChild(a.createTextNode(c+": "));for(var e=a.createElement("select"),c=b.m,g=0,l=c.length;g<l;++g){var n=a.createElement("option");n.text=String(c[g]);n.value=String(c[g]);e.appendChild(n)}f.appendChild(e);e.value=L(b);e.onchange=d;ob(b,function(){e.value=L(b)});return f}
function wc(a,b,c){var a=a.c,d=a.b.createDocumentFragment(),f=a.a("input",{type:"checkbox"});d.appendChild(f);d.appendChild(a.createTextNode(c));f.defaultChecked=L(b);f.checked=L(b);f.onchange=function(){M(b,f.checked)};ob(b,function(){f.checked=L(b)});return d}
function xc(a,b,c,d){var f=a.c,e=f.a("a",{href:"javascript:;"},c+" \u00bb"),c=f.a("a",{href:"javascript:;"},"\u00ab "+c);c.style.marginRight="10px";d=new pc(d,f);a.J[b.e]=d;a=d.H();a=f.a("fieldset","goog-inline-block",f.a("legend",j,c,a.firstChild),a);new $(e,a,k,c);f=f.b.createDocumentFragment();f.appendChild(e);f.appendChild(a);return f}
function yc(a,b,c,d){var a=a.c,f=a.b.createDocumentFragment();f.appendChild(a.createTextNode(c+": "));var e=a.a("input",{value:L(b),size:5,onblur:d});f.appendChild(e);ob(b,function(){e.value=L(b)});return f}
function tc(a,b){var c=oc(b);if(b instanceof P)return wc(a,b,c);else if(b instanceof R){var d=nc(b);return xc(a,b,c,d)}else if(b instanceof N)return d=function(){M(b,this.value)},b.m?vc(a,b,c,d):yc(a,b,c,d);else if(b instanceof O)return d=function(){isNaN(this.value)?this.value=L(b):M(b,+this.value)},b.m?vc(a,b,c,d):yc(a,b,c,d);else if(b instanceof mc)return xc(a,b,b.label,b.Ba);return a.c.a("button",{onclick:u(b.ha,b)},c)}
function mc(a,b){I.call(this,rc+a,"Tweaks within the "+a+" namespace.");this.Ba=b;this.label=a}v(mc,I);var rc="!";wb("Checkbox","boolean\u5024\u306f\u30c1\u30a7\u30c3\u30af\u30dc\u30c3\u30af\u30b9\u3068\u3057\u3066\u8868\u793a\u3055\u308c\u307e\u3059");wb("CheckedCheckbox","boolean\u5024\u306e\u30c7\u30d5\u30a9\u30eb\u30c8\u306ffalse\u3067\u3059\u304c\u3001\u5909\u66f4\u53ef\u80fd\u3067\u3059",i);T(new N("Textbox","\u6587\u5b57\u5217\u306f\u30c6\u30ad\u30b9\u30c8\u30dc\u30c3\u30af\u30b9\u3068\u3057\u3066\u8868\u793a\u3055\u308c\u307e\u3059"),h,h);
T(new N("TextboxWithText","\u6587\u5b57\u5217\u306e\u30c7\u30d5\u30a9\u30eb\u30c8\u306f\u7a7a\u6587\u5b57\u5217\u3067\u3059\u304c\u3001\u5909\u66f4\u53ef\u80fd\u3067\u3059"),"Default text",h);T(new N("Combobox","validValues\u30aa\u30d7\u30b7\u30e7\u30f3\u3092\u4ed8\u3051\u305f\u6587\u5b57\u5217\u306f\u3001\u30c9\u30ed\u30c3\u30d7\u30c0\u30a6\u30f3\u306b\u306a\u308a\u307e\u3059"),"",{I:["Item1","Item2","Item3"]});
T(new O("Numberbox","\u6570\u5024\u306f\u30c6\u30ad\u30b9\u30c8\u30dc\u30c3\u30af\u30b9\u3068\u3057\u3066\u8868\u793a\u3055\u308c\u307e\u3059"),h,h);T(new O("NumberboxWithDefault","\u6570\u5024\u306e\u30c7\u30d5\u30a9\u30eb\u30c8\u306f0\u3067\u3059\u304c\u3001\u5909\u66f4\u53ef\u80fd\u3067\u3059"),100,h);
T(new O("NumberConbobox","validValues\u30aa\u30d7\u30b7\u30e7\u30f3\u3092\u4ed8\u3051\u305f\u6570\u5024\u306f\u3001\u30c9\u30ed\u30c3\u30d7\u30c0\u30a6\u30f3\u306b\u306a\u308a\u307e\u3059"),0,{I:[0,5,10,50]});var zc=new R("BooleanGroup","Boolean\u5024\u306f\u30b0\u30eb\u30fc\u30d7\u5316\u3067\u304d\u307e\u3059");T(zc,h,h);S=zc;wb("GroupItem1","Group item 1");wb("GroupItem2","Group item 2");var S=j,Ac=new qb("Button","\u30dc\u30bf\u30f3\u3067JavaScript\u306e\u5b9f\u884c\u3082\u53ef\u80fd",function(){alert("\u30dc\u30bf\u30f3\u3067JavaScript\u306e\u5b9f\u884c\u3082\u53ef\u80fd")});
Ac.label="\u30b3\u30fc\u30c9\u306e\u5b9f\u884c";T(Ac);new function(){Hb(s("url")?document.getElementById("url"):"url",location.search||"");var a=kc();a?(s("my-tweak-ui")?document.getElementById("my-tweak-ui"):"my-tweak-ui").appendChild(a):Hb(s("my-tweak-ui")?document.getElementById("my-tweak-ui"):"my-tweak-ui","STRIPPED!")};})();
