require 'rake/clean'
require 'erb'

$KCODE = 'U'
$root  = 'http://webos-goodies.googlecode.com/svn/trunk/products/google-gadgets/jsconsole'

TARGETS = ['normal.xml']
CLOBBER.include(TARGETS)

task :default => TARGETS
task :lab => [:lab_webos_goodies_jp, TARGETS].flatten
task :lab_webos_goodies_jp do
  $root = 'http://lab.webos-goodies.jp/jsconsole'
end

def jspack(fname)
  source = IO.read(fname)
  packed = ''
  IO.popen('jsjuicer -sm', 'r+') do |pipe|
    pipe.write(source)
    pipe.close_write
    packed = pipe.read
  end
  packed
end

TARGETS.each do |fname|
  file fname => ['jsconsole.xml', 'script.js'] do |t|
    target = File.basename(t.name, '.xml')
    result = ERB.new(IO.read(t.prerequisites[0]), nil, '>').result(binding)
    File.open(t.name, 'w') do |file|
      file.write(result)
    end
  end
end
